### ISSUE TITLE
[Разработка]: #2. Меню пользователя + страница авторизации/регистрации

### ISSUE THREAD

**Issue by NasDiK** [aliasstudio/bookmaster-front#11]
Задача на анализ #4 

**Что сделать?**

Внимание!!! Base шрифт на всех макетах (продакт промолчал про это) - **Roboto**, в вариациях описанный в ассетах фигмы как "Typography". 
---
Tahoma и Times new Roman недоступны из-за санкций

<details>
<summary>1) Реализовать сайдбар (меню пользователя) для всех страниц системы</summary>

# Сайдбар (Меню пользователя)

Макет (возможно нода криво крепится) - https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=118-2808&mode=design&t=dWvUVMt4KWrB5wVb-0

![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/55022b0b-d754-4e1f-af4f-863a8b5ba6fd)
</details>

<details>
<summary>2) Реализовать страницу авторизации</summary>

# Авторизация/Регистрация

Два режима входа в систему:

## I. Гостевой режим

~~В данном режиме доступно только одна кнопка в сайдбаре (видно в макете фигмы)~~
UPD (25.09.2023 21:24): гостевого режима нет. Никакие страницы не доступны. При переходе на любую страницу кроме 
страницы авторизации - выскакивает [заглушка](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=232-1765&mode=design&t=7a3BipnPmwMpofAn-0). 

Также для неавторизованных пользователей в меню доступна ровно одна кнопка "[Войти](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=232-1765&mode=design&t=7a3BipnPmwMpofAn-0)". При наведении на кнопку появляется тултип "Войти в систему"

## II. Режим авторизованных пользователей

**Общее. Проверка корректности ввода:**
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/faeec2f9-be31-478c-a414-bef5e066b680)

**1) Авторизация**

**Сценарий пользователя:**
1. Пользователь вводит имя пользователя и пароль
1.1*. _При активированном чекбоксе пароль должен быть скрыт звёздочками_
3. Нажимает на кнопку "Войти"

**Всплывают алерты. Поведение**
Проверяем данные на существование в бд.
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/5d49a1a9-1a75-4148-9683-70c69acad627)

**2) Регистрация**
**Сценарий пользователя:**
1. Пользователь вводит имя пользователя и пароль
1.1*. _При активированном чекбоксе пароль должен быть скрыт звёздочками_
3. Нажимает на кнопку "Зарегистрироваться"
4. *Система должна автоматически АВТОРИЗОВАТЬ пользователя*

**Всплывают алерты. Поведение**
Проверяем данные на существование в бд.
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/61b894b7-28d1-4ce4-b83c-163ba42e63d4)

**3) Разавторизация**
Для авторизованных пользователей в сайд-баре доступна кнопка "Выйти"
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/52e956c0-d244-4199-8e45-b8bf28b6758f)
При наведении должен вызываться тултип.

Схема: 
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/052ea37a-2209-44e2-b7b3-7a3a3e750191)

</details>

<details>
 <summary>3) Реализовать инфо-блок над инпутом</summary

 **Все картинки можно взять экспортом из фигмы**

![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/4a523cd9-7c16-4c58-b261-f7b8cb8c486a)
</details>
---

# Требования к адаптивности

1) Сайдбар - фикса. По макету.

2) Авторизация в оставшемся пространстве строго по середине

---

# Дополнительные требования

1) Авторизация **не должна** слетать при нажатии Ф5, хотя-бы какое-то время!

По всем вопросам - Telegram [@Tungusov_Aleksandr](https://t.me/Tungusov_Aleksandr)

---

Правки 01.10.2023 22:40:24

Данные хранить в табличке `users`, `users_roles`, `roles` (#8 )

Атрибуты `users`:
> id: serial, Pk, авто-инкремент, desc: идентификатор пользователя
> username: varchar(255), not null, desc: имя пользователя (логин)
> password: text, not null, desc: шифрованный пароль
> firstName: varchar(255), not null, desc: имя
> middleName: varchar(255), desc: отчество
> lastName: varchar(255), desc: фамилия

Атрибуты `users_roles`
> id: serial, Pk, авто-инкремент
> user_id: Fk(users.id), desc: идентификатор пользователя
> role_id: Fk(roles.id), desc: идентификатор роли

CHECK UNIQUE user_id, role_id

Атрибуты `roles`
> id: serial, Pk, авто-инкремент, desc: идентификатор роли
> name: varchar(255), not null, desc: 'название роли'

При регистрации создаётся:
```typescript
const user = {
  username: 'INPUT_USERNAME',
  password: bcrypt('INPUT_PASSWORD','SHA-256'),
  firstName: 'INPUT_USERNAME' // Пока так, потом с панелью управления придумаем чо нибудь новое))
};
```

## Остальные таблички по ролям будут созданы в #8 !!!!. Это лишь подготовка)

**Comment by Hardome** [comment]
ПРОДАКТ ПИДР

**Comment by NasDiK** [comment]
При регистрации ролей у пользователя нет.
По процессу админ офиса на странице "Панель управления" (будет позже) должен добавить все необходимые права

**Comment by IldarZar** [comment]
@Scoolnik надо запихать 2 mat-form-field, внутри каждого должен быть input. На каждый input поставить formControlName. Чекбокс - не контрол, чисто на клиенте визуалка. Попробуй сразу сделать изменение значение атрибута type у поля с паролем при изменении значения чекбокса. Ну и две кнопки, с ними проблем не будет. На бэке пока логики по авторизации нет, поэтому при нажатии на них ничего происходить не будет.

Посмотри че такое formGroup, formControl. Это всё базовые ангуляровские сущности. 

В материале это делается так:
https://material.angular.io/components/form-field/overview#floating-label

**Comment by IldarZar** [comment]
Страница и боковое меню сделаны. Тестить смысла не вижу, ибо кнопкам некуда редиректить и серьёзного функционала ещё нет. Закрываю задачу.

**Comment by IldarZar** [comment]
Нужно запилить страницу регистрации

**Comment by NasDiK** [comment]
Да не надо!!!

**Comment by IldarZar** [comment]
> Да не надо!!!

Надо Саня, надо

**Comment by IldarZar** [comment]
@Scoolnik в AuthPageComponent надо создать метод register, который будет регистрировать пользователя. Для регистрации, естественно, нужно больше полей, чем при авторизации. Как я уже писал выше, все недостающие поля (firstName, secondName, middleName) будут заполняться какой-нибудь фигней, хоть пустую строку пихай. В AuthService есть метод register, воспользуйся им.
