### ISSUE TITLE
[Разработка]: #1 Сделать общие реиспользуемые компоненты на фронт + проектирование общих вещей

### ISSUE THREAD

**Issue by NasDiK** [aliasstudio/bookmaster-front#2]
Задача на анализ: #1  

<details>

<summary>1) Реализация нотифайеров по всему проекту</summary>

**Зачем**: т.к. у нас SPA, то нам важно, чтобы интерфейс реагировал на все клики пользователя

[Библиотека](https://github.com/scttcper/ngx-toastr) [Тестовый аэродром](https://ngx-toastr.vercel.app/)

Реализация остаётся коробочной из библиотеки

Вариативность: `success | info | warning | error`
Timeout по всему проекту: 3000 мс
ProgressBar: `true`. Animation: `decreasing`
Tap to dismiss: `true`
Position: `top-right`
Title - **не будем использовать**
Max-toasts: `3`
</details>

<details>

<summary>2) Реализовать следующие компоненты для общего использования в проекте</summary>

**Зачем**: чтобы все компоненты в проекте имели высокую связность; ускорение разработки; и моментальное изменение дизайна при необходимости

Ожидаемый внешний вид компонент для проекта из дизайна Figma - [ссылка на Figma](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0)

**Внимание!!!**: в фигме реализован тот минимум который необходим в компонентах. Всего скорее ничего большее чем там мы использовать не будем
Исключение: Button

Компоненты к реализации:

- [x] - [Slider](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0).  [Документация](https://material.angular.io/components/slide-toggle/overview).
- [x] - [Select](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0). [Документация](https://material.angular.io/components/select/overview).
- [x] - [Button](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0). [Документация](https://material.angular.io/components/button/overview).
- [x] - [Checkbox](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0). [Документация](https://material.angular.io/components/checkbox/overview).
- [x] - [Datepicker](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0). [Документация](https://material.angular.io/components/datepicker/overview).
- [x] - [Input](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0). [Документация](https://material.angular.io/components/input/overview).
- [x] - TextField. [Документация](https://material.angular.io/components/input/overview).
- [x] - Icon. [Документация](https://material.angular.io/components/icon/overview).
- [x] - [DropDownMenu](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0). [Документация](https://material.angular.io/components/menu/overview).
- [x] - [Radio](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0). [Документация](https://material.angular.io/components/radio/overview).
- [x] - [Tooltip](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0). [Документация](https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=3-14&mode=design&t=z3gej4GVLcXcpTxV-0).
- [x] - Drawer. [Документация](https://material.angular.io/components/sidenav/examples)
Параметры: sidenavMode: `over`, hasBackdrop: `unset`
Детали параметров проекта в макете (Pages/sharedComponents)
</details>

Условия приёмки - на слово (это исключение, не радуйтесь)

**ВНИМАНИЕ!!! Если видите, что реализовать задуманное невозможно. Тегайте в комментариях создателя задачи. Не страдайте почём зря, всегда можно договориться**

По ТЗ вопрос задавать: https://t.me/Tungusov_Aleksandr

**Comment by NasDiK** [comment]
@aliasstudio Если задачу выполнил - жми close. И открепляй, красавчик)

![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/9368301f-8d95-4245-ac45-e666c4c2190c)

**Comment by Hardome** [comment]
Еще нужна чипса, она тоже есть в angular material
