### ISSUE TITLE
[Тестирование]: #1. Страница авторизации

### ISSUE THREAD

**Issue by Astranomikon** [aliasstudio/bookmaster-front#22]
Тестирование по модулю: [[Разработка]: #2. Меню пользователя + страница авторизации/регистрации](https://github.com/aliasstudio/bookmaster-front/issues/11)
### Сайдбар

1. Проверка на адаптивность пройдена
2. При переходе на страницу авторизации, не авторизированным пользователем, и последующей авторизации сайдбар не до конца расширяет меню. Лечится перезагрузкой в авторизированном режиме и ломается перезагрузкой в гостевом режиме

 
![изображение_2023-11-11_183108197](https://github.com/aliasstudio/bookmaster-front/assets/116378098/16c9b217-d536-4cef-89f6-9eab404d091d)

### Авторизация
**Гостевой режим** 

1. Проверка на переходы на другие страницы в гостевом режиме пройдена
2. Проверка на адаптивность пройдена
3. Не совсем понятно зачем кнопка “Вход” в боковом меню

**Авторизация**

1. Проверка на пустое значение пройдена
2. Проверка на ввод не правильных данных пройдена, но нет алертов описанных в ТЗ (а именно “Пользователя с таким логином не существует” и “Пароль не верный”)
3. Проверка на ввод корректных данных пройдена (проверялось на пользователе "test/test", а так же созданным мною "tost/tost"
4. После авторизации нет перехода на следующее окно (ещё не готово)

**Разавторизация**

1. Проверка на блокировку остальных страниц пройдена

**Comment by IldarZar** [comment]
Сделано

**Comment by IldarZar** [comment]
Навигация по меню пофикшена

**Comment by Astranomikon** [comment]
Закрыто
