### ISSUE TITLE
[Тестирование]: #5 Страница работы с клиентами 

### ISSUE THREAD

**Issue by romankuvshanov** [aliasstudio/bookmaster-front#32]
Полный отчет в pdf файле: 
[Роман Кувшанов Тестирование Страница работы с клиентами.pdf](https://github.com/aliasstudio/bookmaster-front/files/13515718/default.pdf)

**Comment by romankuvshanov** [comment]
Что не работает.

1. На разрешении 816px в ширину и меньше текст на кнопках «Обновить» и «Создать нового клиента» сбивается.
![image](https://github.com/aliasstudio/bookmaster-front/assets/83648973/c9e8f0fa-5d1b-49b8-95ef-4a699a2e3339)

2. Нет импорта клиентов. Не импортированы клиенты из файлов. Я, так понимаю, что это будет сделано перед самой сдачей проекта? Или функционал есть в режиме администратора?  

4. Тест на учитывание фильтра при нажатии на "обновить" не пройден. При нажатии на кнопку "обновить", при выбранном фильтре(заполненном поле поиска клиента), фильтр не учитывается. Я так понимаю, что при применённом поиске нажатие на кнопку "обновить" должно учитывать, то, что написано в поле поиска по ФИО.

https://github.com/aliasstudio/bookmaster-front/assets/83648973/883c05d0-a462-4290-a40d-8e6345dd8bd2



5. Тест на обязательность номера телефона не пройден. Номер телефона должен быть обязательно указан при создании и/или редактировании клиента.
![image](https://github.com/aliasstudio/bookmaster-front/assets/83648973/48056c65-6559-489f-b232-b5673a4fb0d6)



6. Тест на обязательность индекса не пройден. Индекс должен быть обязательно указан при создании и/или редактировании клиента.

![image](https://github.com/aliasstudio/bookmaster-front/assets/83648973/fdb29803-1f47-4f30-abf7-51b015b62796)

**Comment by Scoolnik** [comment]
Семён написал, что адаптив и импорт на фронте не нужны. Остальное пофиксил (pr #33).

**Comment by IldarZar** [comment]
Лайк
