### ISSUE TITLE
[Анализ]: #2 Страница Авторизация/регистрация

### ISSUE THREAD

**Issue by NasDiK** [aliasstudio/bookmaster-front#4]
Макет: https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=53-3436&mode=design&t=aGYCOhVzhoTdPi8d-0

- [ ] - Нарисовать макет
- [x] - В тз на разработку вшить разработку сайд-бара

---

# Требования к адаптивности

1) Сайдбар - фикса. По макету.

2) Авторизация в оставшемся пространстве строго по середине

---

# Сайдбар (Меню пользователя)
Макет (возможно нода криво крепится) - https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=118-2808&mode=design&t=dWvUVMt4KWrB5wVb-0

![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/55022b0b-d754-4e1f-af4f-863a8b5ba6fd)

---

# Авторизация/Регистрация

Два режима входа в систему:

## I. Гостевой режим
В данном режиме доступно только одна кнопка в сайдбаре (видно в макете фигмы)

## II. Режим авторизованных пользователей

**Общее. Проверка корректности ввода:**
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/faeec2f9-be31-478c-a414-bef5e066b680)

**1) Авторизация**

**Сценарий пользователя:**
1. Пользователь вводит имя пользователя и пароль
1.1*. _При активированном чекбоксе пароль должен быть скрыт звёздочками_
3. Нажимает на кнопку "Войти"

**Всплывают алерты. Поведение**
Проверяем данные на существование в бд.
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/5d49a1a9-1a75-4148-9683-70c69acad627)

**2) Регистрация**
**Сценарий пользователя:**
1. Пользователь вводит имя пользователя и пароль
1.1*. _При активированном чекбоксе пароль должен быть скрыт звёздочками_
3. Нажимает на кнопку "Зарегистрироваться"

**Всплывают алерты. Поведение**
Проверяем данные на существование в бд.
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/61b894b7-28d1-4ce4-b83c-163ba42e63d4)

**3) Разавторизация**
Для авторизованных пользователей в сайд-баре доступна кнопка "Выйти"
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/52e956c0-d244-4199-8e45-b8bf28b6758f)
При наведении должен вызываться тултип.

Схема: 
![image](https://github.com/aliasstudio/bookmaster-front/assets/98635531/052ea37a-2209-44e2-b7b3-7a3a3e750191)

**Comment by NasDiK** [comment]
1) Заменить фото
2) Описать поведение сайдбара с учётом прав в системе

**Comment by IldarZar** [comment]
А че закрыли, задача не сделана же
