### ISSUE TITLE
[Разработка]: #3 Страница работы с клиентами

### ISSUE THREAD

**Issue by NasDiK** [aliasstudio/bookmaster-front#5]
В разработке использовать только шаредные компоненты.

<details>
<summary>1) База данных</summary>
Для хранения клиентов необходимо в БД создать табличку **customers** со следующими колонками:

- id 
- name (**обязательное**)
- address (**обязательное**)
- zip (почтовый индекс) (**обязательное**)
- city (**обязательное**)
- phone (**обязательное**)
- email

Айди пользователя должно начинаться с буквы "С" и начинаться с C1001 для первого пользователя, для второго С1002.
Айди должно генерироваться автоматически и не подлежит редактированию пользователем.
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/eb177c95-c787-4d63-9696-1fda8dafa244)
</details>

<details>
<summary>2) Импорт клиентов</summary>
По ТЗ нам необходимо импортнуть клиентов из файла. 
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/39d68668-66ee-4325-b0e1-d599060c5c87)
В папке предоставленной нам есть 4 формата на выбор: 
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/0ac8a831-a961-4b47-a80a-aa626f79241e)
Все 4 файла содержат одинаковых клиентов и их данные. На ваше усмотрение можете релизовать импорт из любого формата.
</details>

<details>
<summary>3) Дизайн</summary>

https://www.figma.com/file/lN9KuCk8tu8F2mIno0Zr4P/Bookmaster-3000?type=design&node-id=81-6169&mode=design&t=UqfXKt1PZ1oB9WS7-0
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/5023b83f-c5fc-438b-a508-82727dcef72e)

Просмотр, создание и редактирование клиентов будет происходить на этой странице. На странице должна быть таблица, кнопки "Создать нового клиента", "Обновить", "Поиск", текстовые поле для поиска клиента (фильтр).

Кнопка "Обновить" - просто обновляет таблицу (получает с БЭКа значения) и учитывает фильтр.
</details>

<details>
<summary>4) Таблица клиентов</summary>
Таблица из angular/material.
В таблице должны быть выведены все колонки из БД.
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/ebe7e285-908c-4c07-8b1d-8a4ab6bc6b07)
Внизу таблицы необходимо выводить количество найденных записей и текущую страницу. **(Реализовано в ангулярской таблице!!!)** Количество записей при пустом фильтре (поле поиска клиента) должно выводить общее количество клиентов. При непустом фильте количество должно выводиться в соответствии с количеством найденных записей.

Таблица должна иметь возможность менять количество отображаемых клиентов и текущую страницу (limit и offset). 
Переключение количества (limit) предлагаю зафиксировать количеством: 10, 20, 50. Тоже есть в таблице из angular/material.

Переключение страницы реализовать двумя стрелочками < и >, которые переключают на предыдущую и следующую страницу.  Кнопка < должна быть неактивна на первой странице, соответственно кнопка >  должна быть неактивна на последней странице. Тоже есть в таблице из angular/material.
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/e7c3bc4d-3962-440a-9a07-6781d9eb5a03)

Для редактирования в таблице есть последний столбик без заголовка, где каждая ячейка это иконка. 
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/759602e7-e270-4ded-82b7-be17beaf08af)
При нажатии на иконку должен появляться dropdown со следующими вариантами:
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/c90a9ed3-d05d-4bd4-beb5-8a71e3347a9c)
 При нажатии на редактировать должен выезжать дровер редактирования клиента.
 При нажатии на кнопку удалить должна появляться модалка:
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/2c37aa24-2c99-4830-9642-d5211d658afd)
Только после подтверждения удаления в модалке удалять клиента.
</details>

<details>
<summary>5)Фильтр</summary>

![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/d4b374a0-4659-4823-a64d-9bcc8743e1f3)

На странице фильтр будет реализован через одно поле, в которое можно писать "ФИО клиента" или "Айди клиента", где "ФИО клиента" - это значение в колонке "name", а  "Айди клиента" - "id". 
Применение фильтра через кнопку "Поиск". 
При нажатии на кнопку "Поиск" - фильтр должен быть применен к таблице (обновление количества записей и самих записей в таблице). Реализацию фильтрации предлагаю сделать на БЭКе, на ФРОНТе выводить только результаты запроса.

Если пользователь стёр в фильтре текст, то вывести все записи в таблицу.

Метод должен сначала пытаться распарсить строку в айдишник, если не получается, то считаем что пользователь ввёл ФИО и ищем по нему. Если распарсил в АЙДИ, то ищем по айди. 
"ФИО клиента" (name в БД) должно проверяться по ILIKE.
"Айди клиента" должно строго проверяться на равенство.
Не забываем, что айди клиента у нас начинается с буквы C####.
</details>

<details>
<summary>6)Создание клиента</summary>
При нажатии на кнопку "Создать нового клиента" должнен выезжать дровер со следующими полями:

- Имя (обязательное)
- Адрес (обязательное)
- Почтовый индекс (обязательное)
- Город (обязательное)
- Номер телефона (обязательное)
- Почта

И кнопками "Очистить", "Создать".
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/f8ef9955-e83c-4092-84dc-de77217941ae)
При нажатии на кнопку "Очистить" значения в полях сбрасываются до дефолтных (пустых).
При нажатии на кнопку "Создать" проверяются поля на пустоту, если хотя бы одно из обязательных пустое - подсвечивать их красным и выводить сообщение "Обязательное поле". Если пользователь повторно жмёт кнопку "Создать", то у заполненных полей убирать предупреждение.
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/604248d3-d035-4c65-a351-b3c8616ee02d)
Если все обязательные поля заполнены - создавать клиента и закрывать дровер, при этом таблица должна обновиться и выехать алерт об успешном создании клиента.
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/26eb1106-e52d-4cca-bb4e-bfd87e9e8e3e)
Если что-то пошло не так, то алерт об ошибке.
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/c4ae759c-b1c9-47a6-8c02-8eac693a2a6b)
</details>

<details>
<summary>7)Редактирование клиента</summary>
 Редактирование пользователь инициирует через дропдаун в таблице.
 
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/dfd44e39-2904-4f12-ba06-d4d7af1c3bbf)

 При нажатии выводить дровер как при создании, но заполнить поля клиента и добавить disabled поле "Айди клиента". Вместо кнопки "Создать" - "Сохранить". 
 Поведение кнопки "Сохранить" такое же как и у кнопки "Создать". 
 
 Алерт успешного изменения клиента.
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/1133453a-979c-4e76-a4e7-f9bd134384bb)
Если что-то пошло не так, то алерт об ошибке.
![image](https://github.com/aliasstudio/bookmaster-front/assets/103805048/f2d8296b-f704-4aa8-adb2-f9f26a65323b)
</details>

**Comment by Hardome** [comment]
Работайте братья

**Comment by IldarZar** [comment]
> Работайте братья
Как скажешь брат

**Comment by IldarZar** [comment]
@Scoolnik основной функционал есть в ветке user-crud. Сделай че-то похожее
